import project1 from "../assets/project-1.png";
import project2 from "../assets/project-2.png";
import project3 from "../assets/project-3.png";
import project4 from "../assets/project-4.png";
import project5 from "../assets/project-5.png";
import project6 from "../assets/project-6.png";
import project7 from "../assets/project-7.jpg";
import project8 from "../assets/project-8.jpg";
import project9 from "../assets/project-9.jpg";

const Items = [
  {
    id: 1,
    mainImage: project1,
    features: [
      "Single Page Application (SPA) for seamless navigation.",
      "User-friendly interface to browse and add items to the cart.",
      "Dynamic quantity adjustment (increase/decrease) for cart items.",
      "Form integration to capture user details for order placement.",
      "Real-time price calculation based on cart items and quantity.",
      "Responsive design for optimal experience on all devices.",
      "404 Page for unmatched routes.",
    ],
    technologies: [
      "React",
      "TailwindCSS",
      "React Leaflet",
      "React Hooks",
      "React icons",
      "Email JS",
      "Framer Motion",
    ],
    title: "Food Order - WebApp",
    description:
      "The Food Order WebApp is a dynamic, user-friendly platform where users can browse and add items to their cart, adjust quantities, fill out order forms, and get real-time price updates. This Single Page Application (SPA) was developed using React.js with Firebase serving as the dummy backend. The app offers smooth transitions, responsive design, and intuitive controls, making it accessible and convenient for all users.",
    category: "personal",
    liveLink: "https://food-order-web-app.vercel.app/",
    codeLink: "https://github.com/kamranahmad2004/Food-order-WebApp",
  },
  {
    id: 2,
    mainImage: project2,
    features: [
      "Browse and select places to visit from a curated list.",
      "Remove selected places easily with a user-friendly interface.",
      "Responsive design for seamless usage on all devices.",
      "Real-time updates for adding or removing places.",
      "404 error page for better user experience in case of navigation errors.",
      "Smooth and interactive UI for enhanced user engagement.",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
    ],
    title: "Place Selector",
    description:
      "Place Selector is a React-based project where users can choose their desired places to visit from a list and remove them if needed. The application is user-friendly, responsive, and serves as a practice project to enhance full-stack development skills using the MERN stack.",
    category: "personal",
    liveLink: "https://umardraz1115.github.io/Demo-not-available/",
    codeLink: "https://github.com/kamranahmad2004/React.js-Projects",
  },
  {
    id: 3,
    mainImage: project3,
    features: [
      "Multiplayer functionality",
      "User-friendly interface",
      "Responsive design",
      "Real-time gameplay updates",
      "Customizable game board size",
      "Score tracking",
      "Dark mode and light mode",
      "Restart game option",
      "Animations and hover effects",
      "Keyboard and touch support",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Router Dom",
      "Tailwind CSS",
      "JavaScript",
      "Vite",
      "Axios",
      "Framer Motion",
      "React Icons",
      "Material UI",
      "React Toastify",
    ],
    title: "Tic Tac Toe",
    description:
      "A multiplayer Tic Tac Toe game built with React.js, featuring real-time gameplay, user-friendly interface, and responsive design.",
    category: "game",
    liveLink: "https://umardraz1115.github.io/Demo-not-available/",
    codeLink: "https://github.com/kamranahmad2004/React.js-Projects",
  },
  {
    id: 4,
    mainImage: project4,

    features: [
      "Browse movies and TV shows",
      "User-friendly interface",
      "Responsive design",
      "Search for movies and TV shows",
      "View movie details and trailers",
      "Dynamic content display",
    ],
    technologies: ["JavaScript", "CSS", "HTML"],
    title: "Netflix Clone",
    description:
      "This is a frontend-only Netflix Clone built with React.js. It offers a user-friendly interface where users can browse, search.",
    category: "personal",
    liveLink: "https://kamranahmad2004.github.io/Sigma-Project/",
    codeLink: "https://github.com/kamranahmad2004/Sigma-Project.git",
  },
  {
    id: 5,
    mainImage: project5,
    features: [
      "Initial Investment Input",
      "Annual Investment Input",
      "Expected Return Input",
      "Duration Input",
      "Live Calculation of Investment Value",
      "Interest (Yearly) Calculation",
      "Total Interest Calculation",
      "Invested Capital Display",
      "Responsive Design",
      "404 Page and many more",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Router Dom",
      "Axios",
      "React Icons",
      "Sweet Alert2",
      "Tailwind CSS",
    ],
    title: "Investment Calculator",
    description:
      "A investment calculator application made with  React & Node.js. It allows users to calculate potential returns based on initial investment, annual investment, expected return, and duration.",
    category: "personal",
    liveLink: "https://umardraz1115.github.io/Demo-not-available/",
    codeLink: "https://github.com/kamranahmad2004/React.js-Projects",
  },
  {
    id: 6,
    mainImage: project6,
    features: [
      "Add tasks",
      "Mark tasks as complete",
      "Delete tasks",
      "Filter tasks by status",
    ],
    technologies: ["JavaScript", "CSS", "HTML"],
    title: "Todo List WebApp",
    description:
      "This Todo List WebApp is a very user-friendly application built using JavaScript and CSS. It allows users to add, mark, and delete tasks, as well as filter them by their status.",
    category: "webapp",
    liveLink: "https://kamranahmad2004.github.io/Todo-List-App/",
    codeLink: "https://github.com/kamranahmad2004/Todo-List-App",
  },
  {
    id: 7,
    mainImage: project7,
    features: [
      "User registration and login",
      "Select the type of question and the difficulty level of the question",
      "Juis time is running and after the time is up it stops automatically",
      "The final results of the answers answered will be shown",
      "Incorrect and correct answer results will be displayed",
      "Responsive Design",
    ],
    technologies: [
      "React",
      "React Vite",
      "Tailwind CSS",
      "Firebase Authentication",
      "Framer Motion",
      "React Firebase Hooks",
      "React Icons",
    ],
    title: "MX-BILL WEBAPP",
    description: "Fullstack open source quiz application",
    category: "business",
    liveLink: "https://umardraz1115.github.io/Demo-not-available/",
    codeLink: "https://github.com/kamranahmad2004/MX-Bill-WebApp.git",
  },
  {
    id: 8,
    mainImage: project8,

    features: [
      "User authentication (Login/Signup)",
      "CRUD operations for tasks",
      "File storage for task attachments",
      "Encrypt and decrypt sensitive data",
      "Responsive design",
      "User-friendly interface",
      "Task filtering and search",
      "Real-time task updates",
      "Task deadline tracking",
    ],
    technologies: [
      "React",
      "Node.js",
      "Express",
      "JWT Authentication",
      "MongoDB",
      "Mongoose",
      "File Storage",
      "Encryption/Decryption",
      "Tailwind CSS",
    ],
    title: "Task Manager WebApp",
    description:
      "A Task Manager WebApp built with React.js for the frontend and Node.js with Express for the backend. It includes user authentication, CRUD operations for tasks, file storage for attachments, and encryption/decryption for sensitive data.",
    category: "personal",
    liveLink: "https://umardraz1115.github.io/Demo-not-available/",
    codeLink: "https://github.com/kamranahmad2004/Task-manager.git",
  },
  {
    id: 9,
    mainImage: project9,
    features: [
      "User authentication (Login/Signup)",
      "CRUD operations for tasks",
      "File storage for task attachments",
      "Encrypt and decrypt sensitive data",
      "Responsive design",
      "User-friendly interface",
      "Task filtering and search",
      "Real-time task updates",
      "Task deadline tracking",
      "Push notifications for task updates",
      "Mobile-friendly interface",
    ],
    technologies: [
      "React Native",
      "Node.js",
      "TypeScript",
      "Express",
      "JWT Authentication",
      "MongoDB",
      "Mongoose",
      "File Storage",
      "Encryption/Decryption",
      "Tailwind CSS",
      "Firebase (for push notifications)",
      "Expo",
    ],
    title: "Teresecrow App (Mobile)",
    description:
      "A Task Manager Mobile App built with React Native for the frontend and Node.js with Express for the backend. It includes user authentication, CRUD operations for tasks, file storage for attachments, encryption/decryption for sensitive data, and push notifications for task updates.",
    category: "business",
    liveLink: "https://umardraz1115.github.io/Demo-not-available/",
    codeLink: "https://github.com/kamranahmad2004/terescrow-agentSir.git",
  },
];

export default Items;
